
Table permissions {
  id smallint [primary key]
  module varchar(100)
  submodule varchar(100)
  action varchar
  created_at timestamp
  updated_at timestamp
}

Table roles_permissions {
  id smallint [primary key]
  role_id smallint
  permission_id smallint
  created_at timestamp
}

Table roles {
  id smallint [primary key]
  name_role varchar(30)
  icon varchar(99)
  created_at timestamp
  updated_at timestamp
}

Table users {
  id integer [primary key]
  role_id integer
  profile_id integer
  auth_code varchar(6)
  password_hash varchar(255)
  auth_attemps tinyint
  is_active bool
  created_at timestamp
  updated_at timestamp
}

Table user_alerts {
  id integer [primary key]
  user_id integer
  token varchar(255)
  platform enum("IOS","WEB","ANDROID")
  is_active bool
  created_at timestamp
}

Table profiles {
  id integer [primary key]
  name varchar(50)
  paternal_surname varchar(50)
  maternal_surname varchar(50)
  email varchar(80)
  phone varchar(20)
  street varchar(60)
  locality varchar(60)
  postal_code varchar(5)
  city varchar(60)
  state varchar(60)
  created_at timestamp
  updated_at timestamp
}

Table devices {
  id integer [primary key]
  user_id integer
  alias varchar(80)
  mac_address varchar(17)
  status enum("active", "inactive")
  version double(2,2)
  auto_tracking bool
  auto_repose bool
  created_at timestamp
  updated_at timestamp
}

Table audits {
  id integer [primary key]
  user_id integer
  ip_address varchar(15)
  action_detail varchar(255)
  after_value object
  before_value object
  operation_type enum("INSERT","DELETE","UPDATE","LOGIN","LOGOUT","READ")
  table_name varchar(100)
  register_id int
  status enum("revised", "pending")
  result_status enum("successed", "failed")
  action_date date
  created_at timestamp
  updated_at timestamp
}

Table system_configuration {
  id integer [primary key]
  lockout tinyint
  auth_attemps tinyint
  updated_at timestamp
}




Table schedule {
  id integer [primary key]
  device_id integer
  label varchar(100)
  start_time date
  end_time date
  active bool
  created_at timestamp
  updated_at timestamp
}

Table device_telemetry {
  id integer [primary key]
  device_id integer
  voltage_data object(energy_in_wh,energy_out_wh,voltage_v,current_a,watts_now)
  servomotor_data object(current_angle_deg)
  created_at timestamp
  updated_at timestamp
}

Table device_daily_summary {
  id integer [primary key]
  device_id integer
  total_energy_in_wh double
  total_energy_out_wh double
  hourly_watts array(object)
  date date
  created_at timestamp
  updated_at timestamp
}



Table device_commands {
  id integer [primary key]
  device_id integer
  topic varchar(50) 
  message object
  status enum("queued", "deilvered")
  delivered_at date
  created_at timestamp
  updated_at timestamp
}


Table sensor_thresholds {
  id integer [primary key]
  device_id integer
  sensor_key varchar(20)
  voltage_thresholds object 
  created_at timestamp
  updated_at timestamp
}


Table alerts {
  id integer [primary key]
  device_id integer
  title varchar(50)
  body varchar(100)
  type varchar(50)
  severity enum("INFORMATIVE","WARNING","CRITICAL")
  is_read bool
  sent_at timestamp
  read_at timestamp
  created_at timestamp
  updated_at timestamp
}







Ref user_role: users.role_id > roles.id 

Ref user_profile: users.profile_id > profiles.id 

Ref device_user: devices.user_id > users.id

Ref roles_permissions: roles_permissions.permission_id > permissions.id

Ref roles_permissions: roles_permissions.role_id > roles.id


Ref alerts_user: user_alerts.user_id > users.id

